export default {
  FETCH_SPACESHIPS_REQUEST: "FETCH_SPACESHIPS_REQUEST",
  FETCH_SPACESHIPS_SUCCESS: "FETCH_SPACESHIPS_SUCCESS",
  FETCH_SPACESHIPS_ERROR:   "FETCH_SPACESHIPS_ERROR",
  LOAD_SPACESHIPS:          "LOAD_SPACESHIPS",
  ADD_TO_CART:              "ADD_TO_CART",
  REMOVE_FROM_CART:         "REMOVE_FROM_CART",
  PURCHASE_FROM_CART:       "PURCHASE_FROM_CART"
}
