export default {
  FETCH_SPACESHIPS_REQUEST: "FETCH_SPACESHIPS_REQUEST",
  FETCH_SPACESHIPS_SUCCESS: "FETCH_SPACESHIPS_SUCCESS",
  FETCH_SPACESHIPS_ERROR:   "FETCH_SPACESHIPS_ERROR",
  LOAD_SPACESHIPS:          "LOAD_SPACESHIPS"
}
